checkpoint_dir: "model/checkpoint"
log_dir: "model/logs"
load_model: null

evaluator:
  num_games: 50
  win_rate: 0.7

training:
  num_iters: 1000
  num_eps: 1000
  batch_size: 800
  eval_freq: 50
  lr: 0.001
  weight_decay: 1e-4

mcts:
  num_simulations: 512
  cpuct: 1.0
  TOTAL_ACTIONS: 33344