checkpoint_dir: "model/checkpoint"
log_dir: "model/logs"
load_model: null

evaluator:
  num_games: 8
  win_rate: 0.75

training:
  num_iters: 3
  num_eps: 8
  batch_size: 320
  eval_freq: 1
  lr: 0.001
  weight_decay: 1e-4

mcts:
  num_simulations: 128
  cpuct: 1.0
  POSSIBLE_ACTIONS: 1500
  TOTAL_ACTIONS: 33344